# Generated by Django 5.0.4 on 2024-05-01 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tattootracker', '0002_tattoo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
